gentoo/kde

- net-im/ktp-text-ui/ktp-text-ui-4.9999.ebuild
Since http://quickgit.kde.org/?p=ktp-text-ui.git&a=commit&h=4b2e10f2202ca8ecb91bcb93fb7f5ffe57b44675 master branch is frameworks-oriented and is not compatible with KDE SC 4.
> [net-im/ktp-text-ui] fix 4.9999 branch

- kde-plasma/kcm-touchpad/kcm-touchpad-9999.ebuild
> [kde-plasma/kcm-touchpad] 'frameworks' branch is now obsolete.

- eclass/kde5-functions.eclass
commit 6c68003fda689d2240ea45df4614166655f6b8ae made live packages depend on
e.g. >=14.12 instead of 5.9999. This change helps out as long as there exist
packages with separate frameworks branch. Alternative would be to add 5.9999
version to add_kdeapps_dep calls in every affected ebuild.
> [eclass] Fix breakage by KDE_APPS_MINIMAL

- kde-apps/knetwalk/knetwalk-9999.ebuild
Package-Manager: portage-2.2.14
> [kde-apps/knetwalk] VIRTUALX_REQUIRED="test"

- kde-apps/lokalize/lokalize-9999.ebuild
The `Translate OpenDocument` button in Lokalize shows the error message `Install translate-toolkit package and retry`.
This PR fixes this.
> [kde-apps/lokalize] Add missing RDEP dev-python/translate-toolkit

- kde-apps/kdepimlibs/kdepimlibs-9999.ebuild
- kde-apps/kdepimlibs/metadata.xml
- kde-apps/kdiagram/kdiagram-9999.ebuild
- kde-apps/kdiagram/metadata.xml
both libraries are optional dependencies for calligra and should be added to the tree before adding calligra
> kdiagram and kdepimlibs KF5 live ebuilds

- kde-plasma/baloo/baloo-9999.ebuild
> [kde-plasma/baloo] Drop dev-libs/xapian, add dev-db/lmdb to DEPEND

- kde-apps/gpgmepp/gpgmepp-9999.ebuild
- kde-frameworks/kwallet/kwallet-9999.ebuild
- kde-frameworks/kwallet/metadata.xml
kde-frameworks/kwallet-5.10.0 needs a similar backport because it does the same find_package calls and links to it even though there is no gpgmepp-5.10.0 yet.
> [kde-frameworks/kwallet] Add USE=gpg and missing DEPENDs

- kde-apps/kmix/files/kmix-5.9999-alsa-optional.patch
- kde-apps/kmix/kmix-5.9999.ebuild
As discovered and tested by ni1s
> [kde-apps/kmix] Fix build with USE=-alsa

- kde-misc/colord-kde/colord-kde-9999.ebuild
- kde-misc/colord-kde/metadata.xml
- kde-misc/kolor-manager/kolor-manager-5.9999.ebuild
- kde-misc/kolor-manager/kolor-manager-9999.ebuild
- media-gfx/synnefo/metadata.xml
- media-gfx/synnefo/synnefo-9999.ebuild
- media-gfx/synnefo
- Any objection to how qt4 flag is used there? From upstream README: USE_Qt4 - use Qt4 even if Qt5 is installed, default is to detect Qt5
> Add kf5-based colour management stuff

- kde-plasma/plasma-desktop/plasma-desktop-5.3.49.9999.ebuild
- kde-plasma/plasma-desktop/plasma-desktop-9999.ebuild
Pull in kde-base/qguiplatformplugin_kde if USE=qt4
Gentoo Bug 549824
I'm wondering if this is it - that would fit cause (plasma-desktop session) and scope (qt4 apps)
> [kde-plasma/plasma-desktop] Add missing RDEPEND

- kde-plasma/kwin/kwin-9999.ebuild
See: http://quickgit.kde.org/?p=kwin.git&a=commitdiff&h=6c0c513
> [kde-plasma/kwin] Increase required libxcb version.

- kde-misc/kcmsystemd/kcmsystemd-1.1.0.ebuild
Should prevent:
```
[…]
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:10 (cmake_policy):
Policy "CMP0037" is not known to this version of CMake.
[…]
```
See also [CMake docs](http://www.cmake.org/cmake/help/v3.0/policy/CMP0037.html).
> Set min. required CMake version

- Documentation/package.mask/kde-applications-15.04:4
- Documentation/package.unmask/.kde-applications-15.04:4/metapackages
- Documentation/package.unmask/kde-applications-15.04:4
- kde-base/kdebase-meta -> kde-apps/kdebase-meta
- Drop SLOT=4 from oxygen-icons, "5" can be installed just as well
> [Documentation] Fix metapackages and regenerate

- kde-apps/kdepim-runtime/kdepim-runtime-9999.ebuild
> [kde-apps/kdepim-runtime] Drop circular dependency

- media-gfx/kgraphviewer/kgraphviewer-9999.ebuild
- media-gfx/kgraphviewer/metadata.xml
Currently doesn't seem to build with Qt 5.5, but upstream is informed already (it's an easy fix).
> [media-gfx/kgraphviewer] Add kf5 version

- kde-plasma/plasma-sdk/files/plasma-sdk-5.3.2-remove-qtwebkit.patch
- kde-plasma/plasma-sdk/plasma-sdk-9999.ebuild
Patch works the same for 5.3.2.
> [kde-plasma/plasma-sdk] Patch out bogus upstream dep

- kde-apps/dolphin-plugins/dolphin-plugins-9999.ebuild
- dropped libkonq, required only for not yet ported hg
- fix Qt slot
> [kde-apps/dolphin-plugins] Fix branch, missing DEPENDs

- eclass/kde4-meta.eclass
kdepim-4.4.11.1 is served as tar.bz2
> [eclass] Fix oldpim bug 555566

- eclass/kde4-base.eclass
E.g. https://forums.gentoo.org/viewtopic-p-7786236.html#7786236
Since kde-apps/kdebase-runtime-meta is a dependency of kdebase-startkde, I figured the latter is redundant here anyway.
> [eclass] Avoid confusion over system configuration

- kde-apps/kdebase-runtime-meta/kdebase-runtime-meta-15.04.3.ebuild
- kde-apps/kdebase-runtime-meta/kdebase-runtime-meta-15.08.49.9999.ebuild
- kde-apps/kdebase-runtime-meta/kdebase-runtime-meta-9999.ebuild
See also https://github.com/gentoo/gentoo-portage-rsync-mirror/pull/183
> [kde-apps/kdebase-runtime-meta] Fix conflict with kf5-based apps

- eclass/kde5.eclass
Do not accidentally comment any directory if KDE_DOC_DIR not exists
> kde5.eclass: Fix release version handbook bug 557390

- kde-apps/kdewebdev-meta/kdewebdev-meta-15.07.90.ebuild
- kde-apps/kdewebdev-meta/kdewebdev-meta-15.08.0.ebuild
- kde-apps/kdewebdev-meta/kdewebdev-meta-15.08.49.9999.ebuild
- kde-apps/kdewebdev-meta/kdewebdev-meta-9999.ebuild
- kde-apps/klinkstatus/klinkstatus-15.07.90.ebuild
- kde-apps/klinkstatus/klinkstatus-15.08.0.ebuild
- kde-apps/klinkstatus/klinkstatus-15.08.49.9999.ebuild
- kde-apps/klinkstatus/klinkstatus-9999.ebuild
It depends on conflicting kde-base/kdepimlibs:4
> kde-apps/kdewebdev-meta: Drop kde-apps/klinkstatus from RDEPEND

- kde-apps/kdeedu-meta/kdeedu-meta-15.07.90.ebuild
- kde-apps/kdeedu-meta/kdeedu-meta-15.08.0.ebuild
- kde-apps/kdeedu-meta/kdeedu-meta-15.08.49.9999.ebuild
While marble was ported to kf5 in 15.08, libkgeomap:4 and packages depending on it continue to pull in kde-apps/marble:4. Let the meta ebuild go out of their way.
> kde-apps/kdeedu-meta: Relax RDEPEND on kde-apps/marble

- kde-plasma/plasma-workspace/files/plasma-workspace-5.4.3-fix-drkonqi.patch
- kde-plasma/plasma-workspace/plasma-workspace-5.4.3.ebuild
- kde-plasma/plasma-workspace/plasma-workspace-5.4.49.9999.ebuild
Not nice: Getting a crash, then going through drkonqi and encountering a usability bug.
> kde-plasma/plasma-workspace: Fix dead button in drkonqi

- eclass/kde5.eclass
This change makes PATCHES handling less error prone, as epatch will find
a pristine directory before there is punting and commenting.
Also tested possible negative impact with the following command in overlay dir:
``for file in $(find . -name "*ebuild" -exec grep -l PATCHES {} \;); do USE="-handbook" ebuild $file clean prepare; done``
...all good
> kde5.eclass: In kde5_src_prepare, place cmake-utils_src_prepare on top

- kde-apps/okular/okular-5.9999.ebuild
Package-Manager: portage-2.2.26
> kde-apps/okular: Depend on >=KF-5.18

- kde-apps/dolphin/dolphin-15.12.49.9999.ebuild
- kde-apps/dolphin/dolphin-9999.ebuild
Package-Manager: portage-2.2.27
> kde-apps/dolphin: Fix ebuild for EAPI 6

- kde-plasma/breeze-gtk/breeze-gtk-5.6.0-r1.ebuild
- kde-plasma/breeze-gtk/files/breeze-gtk-5.6.0-dark.patch
- kde-plasma/kactivitymanagerd/kactivitymanagerd-5.6.0-r1.ebuild
- kde-plasma/plasma-sdk/plasma-sdk-9999.ebuild
Conflict exists with kde-plasma/plasma-desktop-5.6.0
Package-Manager: portage-2.2.27
> kde-plasma/kactivitymanagerd: Workaround file collision

- eclass/kde5-functions.eclass
The variable holding the min version requirement can be named anything.
This should catch most cases, most importantly Qt5 modules.
Fixes akonadi-9999 at least.
> kde5-functions.eclass: Improve punt_bogus_dep

- Documentation/package.mask/kdepim-4.7
Incompatible commit:
https://quickgit.kde.org/?p=kdepimlibs.git&a=commit&h=544410c905ce0ed2d40b33a50dcbb0796d6c91cd
Anyone attempting to remove this mask would need to backport this commit
from kdepim-runtime (nonexistent in KDE PIM 4.4):
https://quickgit.kde.org/?p=kdepim-runtime.git&a=commitdiff&h=d0958cb91c32c72127305e684a70e0d416ff6aa3
> Mask =kde-apps/kdepimlibs-4.14.11* for POP3 breakage

- kde-apps/kdepasswd/kdepasswd-9999.ebuild
Upstream commit 5874a978e0857768dcecc2b3b3da7413f6cdea34
> kde-apps/kdepasswd: Drop KDE_HANDBOOK

- kde-apps/konsole/konsole-16.07.90.ebuild
- kde-apps/konsole/konsole-16.08.49.9999.ebuild
- kde-apps/konsole/konsole-9999.ebuild
Ported away from kdelibs4support in upstream commit
27dec8d02f705c77eef45a2533bed203eec9454f
> kde-apps/konsole: Set KDE_HANDBOOK to optional, fix DEPENDs

- kde-apps/marble/marble-16.07.90.ebuild
- kde-apps/marble/marble-16.08.49.9999.ebuild
- kde-apps/marble/marble-9999.ebuild
- kde-apps/marble/metadata.xml
- Add Qt5SerialPort to aprs DEPENDs now that it's in tree
- Add Qt5{Location,Positioning} support, same USE naming as in PyQt5
- Other packages are using 'designer' so bring marble in line
- Disable marble-qt if USE=kde, it only adds confusion
- Drop unused and deprecated Qt5OpenGL
- Improve DESCRIPTION
> kde-apps/marble: Add USE=dbus,positioning fix DEPENDs, DESCRIPTION

- eclass/kde5.eclass
Uncovered by dev-libs/kreport-3.0.0.
> kde5.eclass: Take care of empty po directory shipped by upstream

- kde-plasma/user-manager/user-manager-9999.ebuild
Upstream commit 4aafaf4e5fea538978f088709ced441a9cd3671e
> kde-plasma/user-manager: Fix DEPENDs

- kde-apps/konqueror/konqueror-9999.ebuild
Upstream commit: 179e924e31113caf36293d494f07a51fc790ade1
> kde-apps/konqueror: Add missing DEPEND

- kde-apps/kget/kget-16.08.49.9999.ebuild
- kde-apps/kget/kget-5.9999.ebuild
- kde-apps/kget/kget-9999.ebuild
Force handbook and tests optional
Improve DESCRIPTION
> kde-apps/kget: kf5_port->frameworks, fix DEPENDs and build options

- eclass/kde5-functions.eclass
- eclass/kde5.eclass
FRAMEWORKS_MINIMAL was always set by kde5-functions.eclass, making the assignments as done with KDE_AUTODEPS since 040cef12f24e64267d5c60bd0b2fbcc5a3280cec a no-op. Since that re-introduces 5.28.0 minimum for KDE Applications 16.12, adding also KDEBASE=kdepim to be able to fix deps for PIM only.
This PR moves assignment of the various KDE related *_MINIMAL variables from ``kde5-functions.eclass`` to ``kde5.eclass`` if ``KDE_AUTODEPS=true``. Effectively no change for the vast majority of ebuilds using kde5.eclass.
> Eclass changes/fixes

- kde-apps/kdecore-meta/kdecore-meta-16.12.49.9999.ebuild
- kde-apps/kdecore-meta/kdecore-meta-9999.ebuild
Historically, these were part of kdebase-meta.
> kde-apps/kdecore-meta: Re-add ported baseapps

- kde-misc/kolor-manager/kolor-manager-9999.ebuild
> kde-misc/kolor-manager: Drop unused DEPEND

- eclass/ecm.eclass
Bug: https://bugs.gentoo.org/836726
I hate having to do that, but the alternative is to disable the option entirely.
> ecm.eclass: Workaround Portage depgraph shortcomings from revdeps' side

- kde-apps/akonadi/akonadi-24.05.49.9999.ebuild
- kde-apps/akonadi/akonadi-9999.ebuild
- kde-apps/akonadi/metadata.xml
- kde-apps/kaccounts-integration/kaccounts-integration-24.05.49.9999.ebuild
- kde-apps/kaccounts-integration/kaccounts-integration-9999.ebuild
- kde-apps/kaccounts-providers/kaccounts-providers-24.05.49.9999.ebuild
- kde-apps/kaccounts-providers/kaccounts-providers-9999.ebuild
- kde-apps/kaccounts-providers/metadata.xml
- kde-frameworks/purpose/metadata.xml
- kde-frameworks/purpose/purpose-5.239.9999.ebuild
- kde-frameworks/purpose/purpose-9999.ebuild
- kde-plasma/plasma-desktop/metadata.xml
- kde-plasma/plasma-desktop/plasma-desktop-6.1.49.9999.ebuild
- kde-plasma/plasma-desktop/plasma-desktop-9999.ebuild
- media-libs/phonon/metadata.xml
- media-libs/phonon/phonon-9999.ebuild
Summary:
kde-apps/kaccounts-providers: Drop IUSE +webengine, add qml USEdep
Let's not kid ourselves: net-libs/signon-ui will pull in dev-qt/qtwebengine
anyway.
kde-apps/kaccounts-integration: Add PDEPEND=kde-apps/kaccounts-providers
kde-apps/kaccounts-integration provides kcm_accounts for systemsettings,
however without kde-apps/kaccounts-providers the list is practically empty
which makes no sense.
So far, only kde-apps/kdenetwork-meta and kde-misc/kio-gdrive had been
pulling it in but we cannot assume every Plasma user would have those
installed.
kde-apps/kaccounts-integration: RDEPEND on signon-kwallet-extension:6
This package already depends on kde-frameworks/kwallet so in this case
we do not introduce a perceived extra dependency. It is also where Arch
Linux chose to put it.
Closes: …
> Cleanup KAccounts situation + phonon backend IUSE change

- Documentation/package.accept_keywords/.kde-plasma-6.2.49.9999/kde-plasma-6.2
- Documentation/package.accept_keywords/.kde-plasma-live/kde-plasma-live
- Documentation/package.accept_keywords/kde-plasma-6.2.49.9999.keywords
- Documentation/package.accept_keywords/kde-plasma-6.2.keywords
- Documentation/package.accept_keywords/kde-plasma-live.keywords
- Documentation/package.mask/kde-plasma-6.2
- Documentation/package.mask/kde-plasma-live
- Documentation/package.unmask/kde-plasma-6.2
- Documentation/package.unmask/kde-plasma-live
- eclass/ecm-common.eclass
- kde-plasma/plasma-login-sessions/metadata.xml
- kde-plasma/plasma-login-sessions/plasma-login-sessions-6.2.49.9999.ebuild
- kde-plasma/plasma-login-sessions/plasma-login-sessions-9999.ebuild
- kde-plasma/plasma-meta/plasma-meta-6.2.49.9999.ebuild
- kde-plasma/plasma-meta/plasma-meta-9999.ebuild
- kde-plasma/plasma-workspace/plasma-workspace-6.2.49.9999.ebuild
- kde-plasma/plasma-workspace/plasma-workspace-9999.ebuild
- sets/kde-plasma-6.2
- sets/kde-plasma-live
Outsourcing available Plasma login sessions from kde-plasma/plasma-workspace.
By doing that, we can afford exposing which sessions are being provided via
IUSE.
We probably do not want people globally setting USE="-wayland" have a default
Plasma Wayland session available to them, and we need to prepare for a world
where KWin can be built without X/xwayland anyway.
> kde-plasma/plasma-workspace: Use kde-plasma/plasma-login-sessions (new package)

- Documentation/CONTRIBUTORS
- Documentation/package.accept_keywords/.kde-plasma-6.2.49.9999/kde-plasma-6.2
- Documentation/package.accept_keywords/.kde-plasma-live/kde-plasma-live
- Documentation/package.accept_keywords/kde-plasma-6.2.49.9999.keywords
- Documentation/package.accept_keywords/kde-plasma-6.2.keywords
- Documentation/package.accept_keywords/kde-plasma-live.keywords
- Documentation/package.mask/kde-plasma-6.2
- Documentation/package.mask/kde-plasma-live
- Documentation/package.unmask/kde-plasma-6.2
- Documentation/package.unmask/kde-plasma-live
- kde-frameworks/kio/kio-9999.ebuild
- kde-plasma/kde-cli-tools/kde-cli-tools-6.2.49.9999.ebuild
- kde-plasma/kde-cli-tools/kde-cli-tools-9999.ebuild
- kde-plasma/keditfiletype/files/keditfiletype-6.2.4-build-restrict.patch
- kde-plasma/keditfiletype/files/keditfiletype-6.2.4-unused-dep.patch
- kde-plasma/keditfiletype/files/keditfiletype-6.2.4-unused-include.patch
- kde-plasma/keditfiletype/keditfiletype-6.2.49.9999.ebuild
- kde-plasma/keditfiletype/keditfiletype-9999.ebuild
- kde-plasma/keditfiletype/metadata.xml
- kde-plasma/plasma-meta/plasma-meta-6.2.49.9999.ebuild
- kde-plasma/plasma-meta/plasma-meta-9999.ebuild
- sets/kde-plasma-6.2
- sets/kde-plasma-live
[kde-frameworks/kio: PDEPEND on kde-plasma/keditfiletype](https://github.com/gentoo/kde/pull/1011/commits/ce6fd88be362f16b1b0621451eb467e6e877e283)
```
KWidgetsAddons has runtime dependency on keditfiletype binary, but as Tier1
Framework only depends on Qt modules. keditfiletype otoh has rather heavy
dependencies (including KIO itself), so it cannot be a dependency of
KWidgetsAddons.
As a compromise, put it into PDEPEND here, since KFileWidget exposes this
KWidgetsAddons component, and revdeps like dolphin and krusader (typical
consumers of KIO) too.
```
Bug: https://bugs.gentoo.org/944812
> kde-plasma/keditfiletype: new package, add 6.2.49.9999, 9999 

- kde-frameworks/kwallet-runtime/files/kwallet-runtime-6.14.0-stdalone.patch
- kde-frameworks/kwallet-runtime/kwallet-runtime-9999.ebuild
- kde-frameworks/kwallet-runtime/metadata.xml
- kde-frameworks/kwallet/files/kwallet-6.14.0-deps.patch
- kde-frameworks/kwallet/kwallet-9999.ebuild
- kde-frameworks/kwallet/metadata.xml
- 1/3 patches is pending upstream so far, the other two are not sure if upstreamable
- `kde-frameworks/kwallet-runtime[legacy-kwallet]` should be forced for the time being
- next step would be adding `kde-frameworks/kwallet-runtime[keyring]` to `virtual/secret-service`
> kde-frameworks/kwallet split to kde-frameworks/kwallet-runtime

- eclass/cmake.eclass
Otherwise the regex might pick up a query of the resulting version var, e.g.:
> if(CMAKE_MINIMUM_REQUIRED_VERSION VERSION_LESS 2.8.12)
Bug: https://bugs.gentoo.org/958923
> cmake.eclass: Avoid false positives by ensuring we find a function call

- eclass/cmake.eclass
- cmake.eclass: Reorder arguments in cmake_src_install cmake_build call
- cmake.eclass: allow nonfatal cmake_src_test
- cmake.eclass: cmake.eclass: Provide cmake_prepare() to solve conflicts w/ other eclass (>=EAPI-8)
- cmake.eclass: fix pms violation
> cmake.eclass improvements
