gentoo/kde

- net-im/ktp-text-ui/ktp-text-ui-9999.ebuild
> [net-im/ktp-text-ui] Add 'net-libs/libkpeople' dependency

- net-libs/libkpeople/libkpeople-9999.ebuild
> [net-libs/libkpeople] Upstream dropped kcontacts dep in 88f8e646

- kde-apps/kompare/kompare-9999.ebuild
> Fix qtprintsupport dependency.

- kde-apps/umbrello/files/umbrello-5.9999-tests-optional.patch
- kde-apps/umbrello/umbrello-5.9999.ebuild
> [kde-apps/umbrello] Add KF5 version

- kde-plasma/ksysguard/ksysguard-5.2.1.ebuild
- kde-plasma/ksysguard/ksysguard-5.2.9999.ebuild
- kde-plasma/ksysguard/ksysguard-9999.ebuild
- kde-plasma/libksysguard/libksysguard-5.2.1.ebuild
- kde-plasma/libksysguard/libksysguard-5.2.9999.ebuild
- kde-plasma/libksysguard/libksysguard-9999.ebuild
- kde-plasma/plasma-workspace/plasma-workspace-5.2.1.ebuild
- kde-plasma/plasma-workspace/plasma-workspace-5.2.9999.ebuild
- kde-plasma/plasma-workspace/plasma-workspace-9999.ebuild
> [plasma-5.2.1] make dep on qtwebkit optional in libksysguard and

- kde-plasma/plasma-sdk/plasma-sdk-9999.ebuild
> [kde-plasma/plasma-sdk] Add blocker on dev-util/plasmate:5

- kde-misc/baloo-kcmadv/baloo-kcmadv-9999.ebuild
gitorious.org shutdown - fixes bug #544848
Package-Manager: portage-2.2.14
> [kde-misc/baloo-kcmadv] Fix HOMEPAGE and EGIT_REPO_URI

- kde-apps/kmplot/kmplot-9999.ebuild
> [kde-apps/kmplot] Frameworks merged to master

- kde-apps/kwordquiz/kwordquiz-9999.ebuild
> [kde-apps/kwordquiz] Frameworks merged to master

- kde-apps/dragon/dragon-9999.ebuild
> [kde-apps/dragon] Frameworks merged to master

- kde-apps/kmplot/kmplot-9999.ebuild
> [kde-apps/kmplot] Add missing DEPENDs

- kde-apps/step/step-9999.ebuild
> [kde-apps/step] Frameworks merged to master

- kde-apps/rocs/rocs-9999.ebuild
> [kde-apps/rocs] Frameworks merged to master

- kde-apps/kstars/files/kstars-15.04.0-use-python2-explicitly.patch
- kde-apps/kstars/kstars-9999.ebuild
- kde-apps/kstars/metadata.xml
> [kde-apps/kstars] Frameworks merged to master

- kde-apps/cantor/cantor-9999.ebuild
Dropped python3 support, build system requires fixing
> [kde-apps/cantor] Frameworks merged to master

- kde-apps/kcachegrind/kcachegrind-5.9999.ebuild
> [kde-apps/kcachegrind] Add kf5 version

- kde-apps/kscreengenie/kscreengenie-9999.ebuild
- kde-apps/kscreengenie/metadata.xml
> [kde-apps/kscreengenie] New package

- app-office/skrooge/metadata.xml
- app-office/skrooge/skrooge-5.9999.ebuild
> [app-office/skrooge] Add kf5 version

- kde-misc/kdeconnect/kdeconnect-9999.ebuild
> [kde-misc/kdeconnect] Add missing DEPENDs

- app-editors/kile/kile-5.9999.ebuild
> [app-editors/kile] Fix deps.

- kde-apps/kwalletmanager/kwalletmanager-15.04.1.ebuild
- kde-apps/kwalletmanager/kwalletmanager-15.04.49.9999.ebuild
- kde-apps/kwalletmanager/kwalletmanager-5.9999.ebuild
- kde-apps/kwalletmanager/kwalletmanager-9999.ebuild
Things just got co-installable.
https://bugs.kde.org/show_bug.cgi?id=346951
http://commits.kde.org/kwallet/bd78050904ce91f134b1f0bde93ed9512613e15f
> [kde-apps/kwalletmanager] Do not autoblock SLOT=4, add USE=minimal

- x11-themes/gnome-breeze/gnome-breeze-9999.ebuild
- x11-themes/gnome-breeze/metadata.xml
This is a little unofficial Breeze like theme for gtk 2 and 3. We can use this until a proper official one is made.
> [x11-themes/gnome-breeze] added

- kde-apps/libkgeomap/libkgeomap-5.9999.ebuild
- kde-apps/libkgeomap/metadata.xml
- net-libs/libkvkontakte/libkvkontakte-5.9999.ebuild
- net-libs/libkvkontakte/metadata.xml
> New packages

- kde-apps/kscreengenie/kscreengenie-9999.ebuild
> [kde-apps/kscreengenie] Fix DEPENDs

- kde-misc/krusader/krusader-5.9999.ebuild
> [kde-misc/krusader] Add kf5 version

- kde-apps/dolphin/dolphin-9999.ebuild
> [kde-apps/dolphin] Add optional USE=thumbnail RDEPENDs

- kde-apps/kgamma/kgamma-5.9999.ebuild
> [kde-apps/kgamma] Add kf5 version

- dev-util/kdevelop-krazy2/kdevelop-krazy2-9999.ebuild
- dev-util/kdevelop-krazy2/metadata.xml
> [dev-util/kdevelop-krazy2] New package

- kde-plasma/plasma-workspace/files/plasma-workspace-5.4-startkde-script.patch
- kde-plasma/plasma-workspace/plasma-workspace-9999.ebuild
> [kde-plasma/plasma-workspace] Update startkde Gentoo FHS patch

- kde-misc/krusader/krusader-9999.ebuild
> [kde-misc/krusader] Frameworks merged to master

- eclass/kde5.eclass
- kde-misc/wacomtablet/metadata.xml
- kde-misc/wacomtablet/wacomtablet-9999.ebuild
Builds fine, note that I don't have hardware to test it.
> [kde-misc/wacomtablet] Add kf5 version

- kde-apps/libkipi/libkipi-5.9999.ebuild
> [kde-apps/libkipi] Fix DEPENDs

- net-misc/knemo/knemo-9999.ebuild
- net-misc/knemo/metadata.xml
> [net-misc/knemo] Add kf5 version

- kde-apps/kig/kig-9999.ebuild
- kde-apps/kscreengenie/kscreengenie-9999.ebuild
- kde-apps/libkdegames/files/libkdegames-tests-optional.patch
- kde-apps/libkdegames/libkdegames-9999.ebuild
- kde-apps/step/step-15.04.3.ebuild
- kde-apps/step/step-9999.ebuild
- sys-block/kpmcore/kpmcore-9999.ebuild
> Fix various DEPENDs

- kde-apps/kasync/kasync-9999.ebuild
- kde-apps/kasync/metadata.xml
> [kde-apps/kasync] New package

- app-office/akonadi-server/akonadi-server-9999.ebuild
> [app-office/akonadi-server] Don't enable ASAN, breaks runtime

- dev-util/kdevelop-cppcheck/kdevelop-cppcheck-9999.ebuild
- dev-util/kdevelop-cppcheck/metadata.xml
- sets/kdevelop-live
> [kdevelop-cppcheck] New package

- dev-util/kdevelop-valgrind/kdevelop-valgrind-9999.ebuild
- dev-util/kdevelop-valgrind/metadata.xml
- sets/kdevelop-live
> [dev-util/kdevelop-valgrind] New package

- app-text/kbibtex/files/kbibtex-fix-cmake.patch
- app-text/kbibtex/kbibtex-9999.ebuild
> [app-text/kbibtex] Switch to feature/kf5 branch

- kde-apps/gpgmepp/gpgmepp-4.14.10.ebuild
- kde-apps/gpgmepp/gpgmepp-4.9999.ebuild
> [kde-apps/gpgmepp] Fix build

- kde-apps/plasma-telepathy-meta/plasma-telepathy-meta-15.07.80.ebuild
- kde-apps/plasma-telepathy-meta/plasma-telepathy-meta-15.08.49.9999.ebuild
> [kde-apps/plasma-telepathy-meta] ktp-call-ui is not part of 15.08

- media-plugins/kipi-plugins/files/kipi-plugins-5.0.0-expoblending.patch
- media-plugins/kipi-plugins/files/kipi-plugins-5.0.0-jpeg.patch
- media-plugins/kipi-plugins/kipi-plugins-5.9999.ebuild
- media-plugins/kipi-plugins/metadata.xml
- net-libs/libmediawiki/libmediawiki-5.9999.ebuild
...including
[net-libs/libmediawiki] Add kf5 version
as an optional dependency.
I've kept the lines for release-version intact for reuse when the first tarball arrives.
> [media-plugins/kipi-plugins] Add kf5 version

- kde-apps/kdepim/files/FindGpgme.cmake
- kde-apps/kdepim/files/kdepim-4.81-includes.patch
- kde-apps/kdepim/files/kdepim-find-gpgme.patch
- kde-apps/kdepim/kdepim-15.08.49.9999.ebuild
- kde-apps/kdepim/kdepim-9999.ebuild
- kde-apps/kdepim/metadata.xml
- profiles/desc/kdepim_features.desc
Monolithic ebuild as a base to split off all the parts.
> [WIP] Add KDE PIM ebuild

- kde-apps/kde4-l10n/files/kde4-l10n-15.07.90-remove-dirs
- kde-apps/kde4-l10n/kde4-l10n-15.07.90.ebuild
> [kde-apps/kde4-l10n] Fix file collisions, bug 557028

- kde-plasma/plasma-workspace/files/plasma-workspace-5.4-consolekit2.patch
- kde-plasma/plasma-workspace/plasma-workspace-5.4.49.9999.ebuild
> kde-plasma/plasma-workspace: Backport consolekit2 support

- kde-plasma/powerdevil/powerdevil-5.4.49.9999.ebuild
- kde-plasma/powerdevil/powerdevil-9999.ebuild
> kde-plasma/powerdevil: Block kde-base/systemsettings[handbook]

- media-plugins/kipi-plugins/kipi-plugins-9999.ebuild
> media-plugins/kipi-plugins: Drop media-libs/herqq DEPEND

- kde-plasma/plasma-workspace/files/plasma-workspace-5.4.3-no-SUID-no-GUID.patch
- kde-plasma/plasma-workspace/plasma-workspace-5.4.3-r1.ebuild
- kde-plasma/plasma-workspace/plasma-workspace-5.4.49.9999.ebuild
- kde-plasma/plasma-workspace/plasma-workspace-9999.ebuild
btw, is there a reason to depend on sys-libs/pam instead of virtual/pam?
> kde-plasma/plasma-workspace: Updates

- kde-apps/kdepim/kdepim-15.12.49.9999.ebuild
- kde-apps/kdepim/kdepim-9999.ebuild
> kde-apps/kdepim: libkdepim was properly split

- kde-apps/kasync/kasync-9999.ebuild
- kde-misc/akonadi-phabricator-resource/akonadi-phabricator-resource-9999.ebuild
- kde-misc/akonadi-phabricator-resource/metadata.xml
Pity it only seems to build with kdepimlibs-15.08.3 right now.
@kensington ? ;)
> kde-misc/akonadi-phabricator-resource: New package

- kde-misc/plasma-applet-weather-widget/plasma-applet-weather-widget-1.6.1.ebuild
- kde-misc/plasma-applet-weather-widget/plasma-applet-weather-widget-9999.ebuild
Package-Manager: portage-2.2.24
> kde-misc/plasma-applet-weather-widget: Fix description

- kde-apps/spectacle/spectacle-9999.ebuild
Package-Manager: portage-2.2.24
> kde-apps/spectacle: Fix DEPEND

- kde-frameworks/kauth/kauth-9999.ebuild
Package-Manager: portage-2.2.26
> kde-frameworks/kauth: Fix dependency

- kde-apps/libkface/libkface-15.12.1.ebuild
- kde-apps/libkface/libkface-15.12.49.9999.ebuild
- kde-apps/libkface/libkface-9999.ebuild
- media-gfx/digikam/digikam-9999.ebuild
In anticipation of opencv-3.1 subslot bump
See also: https://github.com/gentoo/gentoo/pull/752
> kde-apps/libkface, media-gfx/digikam: Add subslot operator

- dev-util/heaptrack/heaptrack-9999.ebuild
- eclass/kde5-functions.eclass
- kde-apps/libkgeomap/libkgeomap-15.12.49.9999.ebuild
- kde-apps/libkgeomap/libkgeomap-9999.ebuild
- kde-plasma/kdecoration/kdecoration-5.5.49.9999.ebuild
- kde-plasma/kdecoration/kdecoration-9999.ebuild
- media-gfx/digikam/digikam-9999.ebuild
- media-plugins/kipi-plugins/kipi-plugins-9999.ebuild
...well, and adding slot override to other add_*_dep functions too.
> Small fixes all around

- kde-apps/akonadi-contact/akonadi-contact-16.03.90.ebuild
- kde-apps/akonadi-contact/akonadi-contact-16.04.49.9999.ebuild
- kde-apps/akonadi-contact/akonadi-contact-9999.ebuild
- kde-apps/akonadi-mime/akonadi-mime-16.03.90.ebuild
- kde-apps/akonadi-mime/akonadi-mime-16.04.49.9999.ebuild
- kde-apps/akonadi-mime/akonadi-mime-9999.ebuild
- kde-apps/akonadi-notes/akonadi-notes-16.03.90.ebuild
- kde-apps/akonadi-notes/akonadi-notes-16.04.49.9999.ebuild
- kde-apps/akonadi-notes/akonadi-notes-9999.ebuild
- kde-apps/akonadi-socialutils/akonadi-socialutils-16.03.90.ebuild
- kde-apps/akonadi-socialutils/akonadi-socialutils-16.04.49.9999.ebuild
- kde-apps/akregator/akregator-16.03.90.ebuild
- kde-apps/akregator/akregator-16.04.49.9999.ebuild
- kde-apps/dolphin/dolphin-16.03.90.ebuild
- kde-apps/dolphin/dolphin-16.04.49.9999.ebuild
- kde-apps/dolphin/dolphin-9999.ebuild
- kde-apps/kdepim-meta/kdepim-meta-16.03.90.ebuild
- kde-apps/kdepim-meta/kdepim-meta-16.04.49.9999.ebuild
- kde-apps/kdepim-meta/kdepim-meta-9999.ebuild
- kde-apps/kdepim/kdepim-16.03.90.ebuild
- kde-apps/kdepim/kdepim-16.04.49.9999.ebuild
- kde-apps/kdepim/kdepim-9999.ebuild
- kde-apps/libksane/libksane-16.03.90.ebuild
- kde-apps/libksane/libksane-16.04.49.9999.ebuild
- kde-apps/libksane/libksane-9999.ebuild
See also: https://github.com/gentoo/gentoo/pull/1219
> kde-apps/libksane: Add block against libksane:4[-minimal]  | Fix kdepimlibs split pkgs

- eclass/kde5.eclass
- kde-apps/akonadiconsole/akonadiconsole-9999.ebuild
- kde-apps/akregator/akregator-9999.ebuild
- kde-apps/blogilo/blogilo-9999.ebuild
- kde-apps/calendarjanitor/calendarjanitor-9999.ebuild
- kde-apps/kaddressbook/kaddressbook-9999.ebuild
- kde-apps/kdepim-apps-libs/kdepim-apps-libs-9999.ebuild
- kde-apps/kdepim/kdepim-9999.ebuild
- kde-apps/knotes/knotes-9999.ebuild
- kde-apps/konsolekalendar/konsolekalendar-9999.ebuild
- kde-apps/ktnef/ktnef-9999.ebuild
- kde-apps/messagelib/messagelib-9999.ebuild
Pushing improvements for existing split ebuilds so kdepim live keeps building, while more split ebuilds are in the works.
> kde-apps KDE PIM: Split building upstream

- kde-apps/ktp-common-internals/ktp-common-internals-16.04.2.ebuild
- kde-apps/ktp-common-internals/ktp-common-internals-16.04.49.9999.ebuild
- kde-apps/ktp-common-internals/ktp-common-internals-9999.ebuild
> kde-apps/ktp-common-internals: remove doxygen references

- kde-plasma/oxygen/oxygen-5.7.49.9999.ebuild
- kde-plasma/oxygen/oxygen-9999.ebuild
> kde-plasma/oxygen: Add USE=qt4, update description

- dev-util/kdevplatform/metadata.xml
> dev-util/kdevplatform: Fix metadata.xml

- dev-util/kdevelop/kdevelop-5.0.9999.ebuild
- dev-util/kdevelop/kdevelop-9999.ebuild
- dev-util/kdevelop/metadata.xml
- dev-util/kdevplatform/files/kdevplatform-5.0.1-unused-deps.patch
- dev-util/kdevplatform/kdevplatform-5.0.9999.ebuild
- eclass/kde5.eclass
- kde-apps/kaddressbook/kaddressbook-9999.ebuild
- kde-apps/marble/marble-9999.ebuild
- kde-apps/messagelib/messagelib-9999.ebuild
> small fixes

- kde-plasma/plasma-desktop/plasma-desktop-9999.ebuild
> kde-plasma/plasma-desktop: baloo-optional patch now upstream

- dev-libs/kreport/kreport-9999.ebuild
- dev-libs/kreport/metadata.xml
- eclass/kde5.eclass
- kde-apps/libkipi/libkipi-16.12.49.9999.ebuild
- kde-apps/libkipi/libkipi-9999.ebuild
- kde-apps/marble/marble-16.12.49.9999.ebuild
- kde-apps/marble/marble-9999.ebuild
libkipi may as well be changed to KDE_SUBSLOT, opinions?
> kde5.eclass: Add KDE_SUBSLOT

- kde-apps/kalarm/kalarm-16.12.49.9999.ebuild
- kde-apps/kalarm/kalarm-9999.ebuild
- kde-apps/kdemultimedia-meta/kdemultimedia-meta-16.12.49.9999.ebuild
- kde-apps/kmail/kmail-16.12.49.9999.ebuild
- kde-apps/kmail/kmail-9999.ebuild
- kde-apps/knotes/knotes-16.12.49.9999.ebuild
- kde-apps/knotes/knotes-9999.ebuild
- kde-apps/korganizer/korganizer-16.12.49.9999.ebuild
- kde-apps/korganizer/korganizer-9999.ebuild
- kde-apps/ktouch/ktouch-16.12.49.9999.ebuild
- kde-apps/ktouch/ktouch-9999.ebuild
- kde-misc/zanshin/zanshin-9999.ebuild
See also:
https://github.com/gentoo/gentoo/pull/3189
https://github.com/gentoo/gentoo/pull/3190
https://github.com/gentoo/gentoo/pull/3191
> Sync with tree

- kde-apps/analitza/analitza-20.03.90.ebuild
- kde-apps/analitza/analitza-20.04.49.9999.ebuild
- kde-apps/analitza/analitza-9999.ebuild
- kde-apps/kdenlive/kdenlive-20.03.90.ebuild
- kde-apps/kdenlive/kdenlive-20.04.49.9999.ebuild
- kde-apps/kdenlive/kdenlive-9999.ebuild
- kde-apps/kdenlive/metadata.xml
- kde-frameworks/plasma/metadata.xml
- kde-frameworks/plasma/plasma-9999.ebuild
- kde-plasma/kinfocenter/kinfocenter-5.18.49.9999.ebuild
- kde-plasma/kinfocenter/kinfocenter-9999.ebuild
- kde-plasma/kinfocenter/metadata.xml
- kde-plasma/kwin/kwin-5.18.49.9999.ebuild
- kde-plasma/kwin/kwin-9999.ebuild
- kde-plasma/kwin/metadata.xml
- media-gfx/digikam/digikam-7.0.0_beta2.ebuild
- media-gfx/digikam/digikam-9999.ebuild
- media-gfx/krita/krita-9999.ebuild
> */*: IUSE gles2 -> gles2-only

- eclass/ecm-common.eclass
- kde-frameworks/purpose-kaccounts-services/purpose-kaccounts-services-9999.ebuild
- kde-misc/kio-gdrive-common/kio-gdrive-common-24.08.49.9999.ebuild
- kde-misc/kio-gdrive-common/kio-gdrive-common-9999.ebuild
> ecm-common.eclass: Fix pkg_setup()

- kde-plasma/plasma-meta/plasma-meta-6.3.91.ebuild
- kde-plasma/plasma-meta/plasma-meta-6.4.49.9999.ebuild
- kde-plasma/plasma-meta/plasma-meta-9999.ebuild
To avoid running into kde-plasma/powerdevil won't start bug.
Bug: https://bugs.gentoo.org/956312
> kde-plasma/plasma-meta: RDEPEND on >=sys-apps/systemd-257
